### ISSUE TITLE
[WIP] Player guilds proposal

### ISSUE THREAD

**Issue by Arcanorum** [Arcanorum/rogueworld#144]
### Category
- Other

### Feature description

Currently there are several problems:
- There is a lack of competition for the available resources across the overworld.
- There is a lack of ways to use up crafted items without just dumping them. Far more items get produced than are being consumed by what the current game systems require.
- There is a lack of a substantial end goal for players to work towards.
- There is a lack of collective investment in the game. Everything so far is about personal advancement, such as gaining items and stat levels.

Guilds made and ran by players could help to solve some of these problems.

# Design pillars
## Reinforce character archetype fantasies
Allow players to model a guild in the image of certain specialist playstyles, instead of every guild trying to be everything. i.e. a merchants guild, an assassins guild, etc.

## Expand the world
- Should open up more opportunities for interesting encounters around the game world, not divide it up into smaller, insular, gated, private communities.
- Should be something that anyone can interact with at any time, not by invite only. Other players cannot strictly exclude other players from engaging in the content in some way.
- Should not get in the way of existing content for those that do not want to take part, players cannot force other players to engage in the content in a certain way. You can do everything else just fine without guilds being an obstruction.

## Impermanence
- Once established, they do not just become a permanent static feature of the world. There should always be the possibility that a guild can be toppled and that something else may take it's place.
- There shouldn't be a definitive end state that a guild can reach, at which point they have "completed" the guild content.

# Core features
## Stats
Each guild would have a set of stats, the same as a player.
When a member of the guild gain stat exp, their guild also gains an amount of exp in the same stat. i.e. When a member gains weaponry exp, the guild they are in also gains some weaponry exp.
These guild stats would be the requirements to unlock various other guild features.
When enough guild stat exp is gained, the guild stat levels up, like for a player.
Each guild stat has a maximum level, at which exp gained from members stops being added.
The max level for a stat can be increased by building bookshelf structures. i.e. Building a ranged bookshelf would increase the max level of the ranged stat for the guild, allowing further ranged exp to be gained.
When a bookshelf is destroyed, the max level of the corresponding stat is lowered. If the guild stat level was above this new max after being lowered, then any exp in that stat over the max is lost.

## Bases
See #169 

## Trainable friendly mobs
Convert crafted items into troops for your guild that will defend your base from invaders. For example, a guild could train a knight mob which would cost an iron sword and dungium armour.
- Acts as an item sink
- Allows guilds to be defended somewhat while players are not present.

## Passive bonuses
- Benefits offered to all guild members.
- Specific to the archetypes that the guild wants to focus on.

## Guild chat
A new global chat channel that can only be used by guild members.

### Notes

Guild panel draft:
![image](https://user-images.githubusercontent.com/9785268/126075934-f6dc955c-ffe7-4134-abdb-489a5834e025.png)

**Comment by Sebasflow23** [comment]
Suggestions:
Make guild base map expandable with glory.
You train a zombie knight, by getting a zombie to follow you, and then giving it armor and a weapon.

Is this next update?

**Comment by Arcanorum** [comment]
> Suggestions:
> Make guild base map expandable with glory.
There are some technical limitations with expandable maps. Currently the map data is sent to the client when the game is loaded, so if the size/shape of the map can change then it needs to be sent as extra data to anyone who enters that zone.
The maps would be large enough that you wouldn't typically be able to fill it with structures anyway, and they would have enough space that there are several viable options for where to start building while giving attackers some options of where to attack from.

> You train a zombie knight, by getting a zombie to follow you, and then giving it armor and a weapon.
That sounds like a separate feature request as an extension to necromancy.
If you mean in general about how the trainable units would work, I'll attach a mockup of what I had in mind for the interface.

> Is this next update?
No. It is still being designed. Maybe update after next if I can find some more helpers, as this will be quite a large amount of changes.

**Comment by Sebasflow23** [comment]
Hi Arcan!
